package dev.lpsmods.morefood.core;

import dev.lpsmods.morefood.Constants;
import dev.lpsmods.morefood.item.*;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;

public class ModItems {
    public static final Item ALMONDS;
    public static final Item ALMOND_SACK;
    public static final Item ALMOND_SAPLING;
    public static final Item AMERICANO;
    public static final Item APPLESAUCE;
    public static final Item APPLE_ICECRUSH;
    public static final Item APPLE_JUICE;
    public static final Item APPLE_PIE;
    public static final Item APPLE_RASPBERRY_ICECRUSH;
    public static final Item APPLE_RASPBERRY_PIE;
    public static final Item APPLE_SAPLING;
    public static final Item APPLE_SODA;
    public static final Item AVOCADO;
    public static final Item AVOCADO_SACK;
    public static final Item AVOCADO_SAPLING;
    public static final Item BACON;
    public static final Item BACON_EGG_MUFFIN;
    public static final Item BACON_EGG_SANDWICH;
    public static final Item BAKED_SWEET_POTATO;
    public static final Item BANANA;
    public static final Item BANANA_ICE_CREAM;
    public static final Item BANANA_MILKSHAKE;
    public static final Item BANANA_SACK;
    public static final Item BANANA_SAPLING;
    public static final Item BANANA_SMOOTHIE;
    public static final Item BARLEY_SEEDS;
    public static final Item BARLEY_SEED_SACK;
    public static final Item BAT_MEAT;
    public static final Item BEANS;
    public static final Item BEAN_SACK;
    public static final Item BEAN_SEEDS;
    public static final Item BEEF_GOULASH;
    public static final Item BEEF_RAVIOLI;
    public static final Item BEEF_STEW;
    public static final Item BEEF_SUB;
    public static final Item BEER;
    public static final Item BEER_GLASS;
    public static final Item BERRY_ICECRUSH;
    public static final Item BERRY_JUICE;
    public static final Item BERRY_PIE;
    public static final Item BERRY_SMOOTHIE;
    public static final Item BERRY_SODA;
    public static final Item BEVERAGE_CUP;
    public static final Item BLACK_CANDY;
    public static final Item BLUEBERRIES;
    public static final Item BLUEBERRY_SACK;
    public static final Item BLUEBERRY_SEEDS;
    public static final Item BLUEBERRY_SEED_SACK;
    public static final Item BLUEBERRY_SYRUP;
    public static final Item BLUE_CANDY;
    public static final Item BLUE_CUPCAKE;
    public static final Item BOTTLE;
    public static final Item BOTTLED_BEER;
    public static final Item BOTTLED_CIDER;
    public static final Item BOTTLED_RED_WINE;
    public static final Item BOTTLED_WHITE_WINE;
    public static final Item BREADSTICKS;
    public static final Item BREADSTICKS_WITH_GLOWBERRY_JAM;
    public static final Item BREADSTICKS_WITH_JAM;
    public static final Item BREADSTICKS_WITH_PEANUT_BUTTER;
    public static final Item BREAD_LOAF;
    public static final Item BREAKFAST_SUB;
    public static final Item BROWN_CANDY;
    public static final Item BUCKWHEAT;
    public static final Item BUCKWHEAT_SACK;
    public static final Item BURGER_BUN;
    public static final Item BURNT_MARSHMALLOW_ON_A_STICK;
    public static final Item BURRITO;
    public static final Item BUTTER;
    public static final Item CABBAGE;
    public static final Item CABBAGE_SACK;
    public static final Item CABBAGE_SEEDS;
    public static final Item CABBAGE_SEED_SACK;
    public static final Item CAKE_WITH_CHERRIES;
    public static final Item CANDY_CORN;
    public static final Item CANDY_CORN_BOWL;
    public static final Item CAPPUCCINO;
    public static final Item CAPPUCCINO_DRINK_MIX;
    public static final Item CARTON;
    public static final Item CEREAL;
    public static final Item CHEESE_BUCKET;
    public static final Item CHEESE_PIE;
    public static final Item CHEESE_SPREAD;
    public static final Item CHEESE_TOASTIE;
    public static final Item CHEESE_TORTELLINI;
    public static final Item CHEESE_WEDGE;
    public static final Item CHERRIES;
    public static final Item CHERRY_SACK;
    public static final Item CHICKEN_FAJITA;
    public static final Item CHICKEN_NUGGET;
    public static final Item CHICKEN_PIE;
    public static final Item CHICKEN_SELECT;
    public static final Item CHICKEN_SELECT_BOX;
    public static final Item CHICKEN_SOUP;
    public static final Item CHICKEN_SUB;
    public static final Item CHILI;
    public static final Item CHOCOLATE_BANANA_MUFFIN;
    public static final Item CHOCOLATE_CAKE;
    public static final Item CHOCOLATE_CHUNK_OATMEAL_COOKIE;
    public static final Item CHOCOLATE_CHUNK_OATMEAL_COOKIE_SACK;
    public static final Item CHOCOLATE_DONUT;
    public static final Item CHOCOLATE_ICE_CREAM;
    public static final Item CHOCOLATE_MILKSHAKE;
    public static final Item CHOCOLATE_PEANUT_BUTTER;
    public static final Item CHOCOLATE_PIE;
    public static final Item CHOCOLATE_PROTEIN_DRINK;
    public static final Item CHOCOLATE_PROTEIN_DRINK_MIX;
    public static final Item CHOCOLATE_PUDDING;
    public static final Item CIDER;
    public static final Item COCOA_BEVERAGE;
    public static final Item COCOA_BEVERAGE_POWDER;
    public static final Item COCONUT;
    public static final Item COCONUT_MEAT;
    public static final Item COCONUT_MILK;
    public static final Item COCONUT_SACK;
    public static final Item COFFEE_BEANS;
    public static final Item COFFEE_BEAN_SACK;
    public static final Item COFFEE_DONUT;
    public static final Item COOKED_BACON;
    public static final Item COOKED_BAT_MEAT;
    public static final Item COOKED_CHICKEN_NUGGET;
    public static final Item COOKED_CHICKEN_PIECE;
    public static final Item COOKED_HAMBURGER_PATTY;
    public static final Item COOKED_HOGLIN_MEAT;
    public static final Item COOKED_HOT_DOG_SAUSAGE;
    public static final Item COOKED_MARSHMALLOW_ON_A_STICK;
    public static final Item COOKED_PUMPKIN_SEEDS;
    public static final Item COOKED_SALTED_PUMPKIN_SEEDS;
    public static final Item COOKED_SAUSAGE;
    public static final Item COOKED_VEGANBURGER_PATTY;
    public static final Item COOKED_WEDGES;
    public static final Item COPPER_KNIFE;
    public static final Item CORN;
    public static final Item CORNBREAD;
    public static final Item CORN_COB;
    public static final Item CORN_COB_SACK;
    public static final Item CORN_FLOUR;
    public static final Item CORN_FLOUR_SACK;
    public static final Item CORN_SACK;
    public static final Item CRACKERS;
    public static final Item CRACKERS_WITH_CHEESE;
    public static final Item CRACKERS_WITH_CHOCOLATE_PEANUT_BUTTER;
    public static final Item CRACKERS_WITH_GLOWBERRY_JAM;
    public static final Item CRACKERS_WITH_JALAPENO_CHEESE;
    public static final Item CRACKERS_WITH_JAM;
    public static final Item CRACKERS_WITH_PEANUT_BUTTER;
    public static final Item CRANBERRIES;
    public static final Item CRANBERRY_SACK;
    public static final Item CRANBERRY_SEEDS;
    public static final Item CREAM_CARTON;
    public static final Item CREATIVE_HUNGER;
    public static final Item CUSTARD;
    public static final Item CUT_BREAD;
    public static final Item CUT_BREAD_WITH_CHEESE;
    public static final Item CUT_BREAD_WITH_CHOCOLATE_PEANUT_BUTTER;
    public static final Item CUT_BREAD_WITH_GLOWBERRY_JAM;
    public static final Item CUT_BREAD_WITH_JALAPENO_CHEESE;
    public static final Item CUT_BREAD_WITH_JAM;
    public static final Item CUT_BREAD_WITH_PEANUT_BUTTER;
    public static final Item CUT_FRIES;
    public static final Item CUT_SWEET_POTATO;
    public static final Item CYAN_CANDY;
    public static final Item DARK_CHOCOLATE;
    public static final Item DARK_CHOCOLATE_COVERED_APPLE;
    public static final Item DIAMOND_KNIFE;
    public static final Item DOUGH;
    public static final Item DRIED_CRANBERRIES;
    public static final Item DRIED_RAISENS;
    public static final Item EGGPLANT;
    public static final Item EGGPLANT_SACK;
    public static final Item EGGPLANT_SEEDS;
    public static final Item EGGPLANT_SEED_SACK;
    public static final Item FLOUR;
    public static final Item FLOUR_SACK;
    public static final Item FRIED_EGG;
    public static final Item FRIED_SQUID;
    public static final Item FRIES;
    public static final Item FRY_WRAPPER;
    public static final Item FUNGUS_STEW;
    public static final Item GARLIC;
    public static final Item GARLIC_BULB;
    public static final Item GARLIC_MASHED_POTATOES;
    public static final Item GARLIC_SACK;
    public static final Item GELATIN;
    public static final Item GHAST_COOKIE;
    public static final Item GHERKIN;
    public static final Item GHERKIN_SACK;
    public static final Item GHERKIN_SEEDS;
    public static final Item GHERKIN_SEED_SACK;
    public static final Item GLASS_SHARD;
    public static final Item GLOWBERRY_ICECRUSH;
    public static final Item GLOWBERRY_JAM;
    public static final Item GLOWBERRY_JELLY_SANDWICH;
    public static final Item GLOWBERRY_JUICE;
    public static final Item GLOWBERRY_PIE;
    public static final Item GLOWBERRY_SMOOTHIE;
    public static final Item GLOWBERRY_SODA;
    public static final Item GOLDEN_KNIFE;
    public static final Item GRAPE;
    public static final Item GRAPE_BEVERAGE;
    public static final Item GRAPE_BEVERAGE_POWDER;
    public static final Item GRAPE_ICECRUSH;
    public static final Item GRAPE_JUICE;
    public static final Item GRAPE_SACK;
    public static final Item GRAPE_SEEDS;
    public static final Item GRAPE_SEED_SACK;
    public static final Item GRAPE_SMOOTHIE;
    public static final Item GRAPE_SODA;
    public static final Item GRAY_CANDY;
    public static final Item GREEN_CANDY;
    public static final Item GUACAMOLE;
    public static final Item HAMBURGER;
    public static final Item HAMBURGER_PATTY;
    public static final Item HASH_BROWNS;
    public static final Item HOGLIN_MEAT;
    public static final Item HOPS;
    public static final Item HOPS_SACK;
    public static final Item HOPS_SEEDS;
    public static final Item HOPS_SEED_SACK;
    public static final Item HOT_BEVERAGE_CUP;
    public static final Item HOT_COCOA;
    public static final Item HOT_COFFEE;
    public static final Item HOT_DOG;
    public static final Item HOT_DOG_BUN;
    public static final Item HOT_DOG_SAUSAGE;
    public static final Item HOT_TEA;
    public static final Item ICECRUSH_GLASS;
    public static final Item ICED_DONUT;
    public static final Item ICE_CREAM_BOWL;
    public static final Item ICE_CREAM_CONE;
    public static final Item ICING;
    public static final Item IRON_KNIFE;
    public static final Item JALAPENO_CHEESE_BUCKET;
    public static final Item JALAPENO_CHEESE_PIE;
    public static final Item JALAPENO_CHEESE_SPREAD;
    public static final Item JALAPENO_CHEESE_TOASTIE;
    public static final Item JALAPENO_CHEESE_WEDGE;
    public static final Item JALAPENO_ROUND_CHEESE;
    public static final Item JAM;
    public static final Item JAR;
    public static final Item JELLY_SANDWICH;
    public static final Item KEBAB;
    public static final Item KETCHUP;
    public static final Item LARGE_BOWL;
    public static final Item LARGE_PUMPKIN_PALE;
    public static final Item LEMON;
    public static final Item LEMON_ICECRUSH;
    public static final Item LEMON_JUICE;
    public static final Item LEMON_LIME_BEVERAGE;
    public static final Item LEMON_LIME_BEVERAGE_POWDER;
    public static final Item LEMON_PIE;
    public static final Item LEMON_SACK;
    public static final Item LEMON_SAPLING;
    public static final Item LEMON_SODA;
    public static final Item LETTUCE;
    public static final Item LETTUCE_SACK;
    public static final Item LETTUCE_SEEDS;
    public static final Item LETTUCE_SEED_SACK;
    public static final Item LIGHT_BLUE_CANDY;
    public static final Item LIGHT_GRAY_CANDY;
    public static final Item LIME_CANDY;
    public static final Item MACCHIATO;
    public static final Item MAGENTA_CANDY;
    public static final Item MAPLE_MUFFIN;
    public static final Item MAPLE_SAP_BUCKET;
    public static final Item MAPLE_SYRUP;
    public static final Item MAPLE_SYRUP_BUCKET;
    public static final Item MARSHMALLOW;
    public static final Item MARSHMALLOW_ON_A_STICK;
    public static final Item MASHED_POTATOES;
    public static final Item MEAL_READY_TO_EAT;
    public static final Item MELON_ICECRUSH;
    public static final Item MELON_JUICE;
    public static final Item MILK_CARTON;
    public static final Item MILK_CHOCOLATE;
    public static final Item MILK_CHOCOLATE_COVERED_APPLE;
    public static final Item MIXED_FRUIT_ICECRUSH;
    public static final Item MIXED_FRUIT_JUICE;
    public static final Item MIXED_FRUIT_SMOOTHIE;
    public static final Item MOCHA;
    public static final Item MUFFIN_BUN;
    public static final Item NETHERITE_APPLE;
    public static final Item NETHERITE_KNIFE;
    public static final Item NETHERWART_CHICKEN_SOUP;
    public static final Item NETHERWART_MUSHROOM_SOUP;
    public static final Item NETHER_COOKIE;
    public static final Item NETHER_COOKIE_SACK;
    public static final Item NOODLES;
    public static final Item OATMEAL;
    public static final Item OATMEAL_COOKIE;
    public static final Item OATMEAL_COOKIE_SACK;
    public static final Item OATS;
    public static final Item OAT_SACK;
    public static final Item OAT_SEEDS;
    public static final Item OAT_SEED_SACK;
    public static final Item OIL;
    public static final Item OLIVES;
    public static final Item OLIVES_SACK;
    public static final Item OLIVE_SAPLING;
    public static final Item ONIGIRI;
    public static final Item ONION;
    public static final Item ONION_RINGS;
    public static final Item ONION_SACK;
    public static final Item ONION_SEEDS;
    public static final Item ONION_SEED_SACK;
    public static final Item ORANGE;
    public static final Item ORANGE_BEVERAGE;
    public static final Item ORANGE_BEVERAGE_POWDER;
    public static final Item ORANGE_CANDY;
    public static final Item ORANGE_ICECRUSH;
    public static final Item ORANGE_JELLY;
    public static final Item ORANGE_JUICE;
    public static final Item ORANGE_SACK;
    public static final Item ORANGE_SAPLING;
    public static final Item ORANGE_SODA;
    public static final Item PALM_SAPLING;
    public static final Item PANCAKES;
    public static final Item PANCAKE_MIX;
    public static final Item PASTA;
    public static final Item PEANUT;
    public static final Item PEANUT_BUTTER;
    public static final Item PEANUT_BUTTER_JELLY_SANDWICH;
    public static final Item PEANUT_SACK;
    public static final Item PEANUT_SEEDS;
    public static final Item PEANUT_SEED_SACK;
    public static final Item PEPPER;
    public static final Item PEPPERMINT;
    public static final Item PEPPERMINT_EXTRACT;
    public static final Item PEPPERMINT_RING;
    public static final Item PEPPERMINT_SEEDS;
    public static final Item PEPPER_SACK;
    public static final Item PEPPER_SEEDS;
    public static final Item PEPPER_SEED_SACK;
    public static final Item PICKLES;
    public static final Item PIE_BASE;
    public static final Item PINK_CANDY;
    public static final Item PINK_CUPCAKE;
    public static final Item PINK_ICE_DONUT;
    public static final Item PITTA_BREAD;
    public static final Item PIZZA;
    public static final Item PIZZA_BASE;
    public static final Item PIZZA_SLICE;
    public static final Item PLAIN_DONUT;
    public static final Item PLUM;
    public static final Item PLUM_PIE;
    public static final Item PLUM_SACK;
    public static final Item PLUM_SAPLING;
    public static final Item POISONOUS_SWEET_POTATO;
    public static final Item POISONOUS_SWEET_POTATO_SACK;
    public static final Item POISON_BERRIES;
    public static final Item POISON_BERRY_SACK;
    public static final Item POPCORN;
    public static final Item POPCORN_BUCKET;
    public static final Item PORK_PIE;
    public static final Item PORK_SAUSAGE_BURGER;
    public static final Item POUND_CAKE;
    public static final Item PRETZEL;
    public static final Item PRETZEL_NUGGETS;
    public static final Item PRETZEL_STICKS;
    public static final Item PULLED_BEEF_BURGER;
    public static final Item PULP;
    public static final Item PURPLE_CANDY;
    public static final Item RAINBOW_CAKE;
    public static final Item RAMEN_NOODLES;
    public static final Item RASPBERRY;
    public static final Item RASPBERRY_SACK;
    public static final Item RASPBERRY_SEEDS;
    public static final Item RASPBERRY_SEED_SACK;
    public static final Item RASPBERRY_SMOOTHIE;
    public static final Item RASPBERRY_SYRUP;
    public static final Item REDWHITEBLUE_CAKE;
    public static final Item RED_CANDY;
    public static final Item RED_WINE;
    public static final Item RICE;
    public static final Item RICE_PUDDING;
    public static final Item RICE_SACK;
    public static final Item RICE_SEEDS;
    public static final Item RICE_SEED_SACK;
    public static final Item ROASTED_PEANUT;
    public static final Item ROASTED_SOYBEANS;
    public static final Item ROASTED_SUNFLOWER_SEEDS;
    public static final Item ROTTEN_PORKCHOP;
    public static final Item ROUND_CHEESE;
    public static final Item SALT;
    public static final Item SASHIMI;
    public static final Item SAUSAGE;
    public static final Item SAUSAGE_EGG_MUFFIN;
    public static final Item SAUSAGE_EGG_SANDWICH;
    public static final Item SHROOMLIGHT_SLICES;
    public static final Item SMALL_PUMPKIN_PALE;
    public static final Item SMOKED_ALMONDS;
    public static final Item SODA_CAN;
    public static final Item SOYBEANS;
    public static final Item SOYBEAN_SACK;
    public static final Item SPAGHETTI;
    public static final Item SPAGHETTI_WITH_MEATBALLS;
    public static final Item SPARKLING_WATER_BOTTLE;
    public static final Item SPARKLING_WATER_BUCKET;
    public static final Item SPEARMINT;
    public static final Item SPINACH;
    public static final Item SPINACH_FETTUCCINE;
    public static final Item SPINACH_SACK;
    public static final Item SPINACH_SEEDS;
    public static final Item SPINACH_SEED_SACK;
    public static final Item SQUID;
    public static final Item STARCH;
    public static final Item STEAK_PIE;
    public static final Item STONE_KNIFE;
    public static final Item STRAWBERRY;
    public static final Item STRAWBERRY_DONUT;
    public static final Item STRAWBERRY_ICECRUSH;
    public static final Item STRAWBERRY_ICE_CREAM;
    public static final Item STRAWBERRY_JELLY;
    public static final Item STRAWBERRY_JUICE;
    public static final Item STRAWBERRY_MILKSHAKE;
    public static final Item STRAWBERRY_PIE;
    public static final Item STRAWBERRY_SACK;
    public static final Item STRAWBERRY_SEEDS;
    public static final Item STRAWBERRY_SEED_SACK;
    public static final Item STRAWBERRY_SMOOTHIE;
    public static final Item STRAWBERRY_SODA;
    public static final Item STRAWBERRY_SYRUP;
    public static final Item SUB_BUN;
    public static final Item SUB_WRAPPER;
    public static final Item SUGAR_COOKIE;
    public static final Item SUGAR_COOKIE_SACK;
    public static final Item SUSHI;
    public static final Item SWEET_MASHED_POTATOES;
    public static final Item SWEET_POTATO;
    public static final Item SWEET_POTATO_FRIES;
    public static final Item SWEET_POTATO_SACK;
    public static final Item TACO;
    public static final Item TEA_LEAF_SACK;
    public static final Item TEA_LEAVES;
    public static final Item TEA_SEEDS;
    public static final Item TEA_SEED_SACK;
    public static final Item TOAST;
    public static final Item TOFFEE;
    public static final Item TOFFEE_DONUT;
    public static final Item TOFFEE_ICE_CREAM;
    public static final Item TOFFEE_LATTE;
    public static final Item TOFFEE_PIE;
    public static final Item TOMATO;
    public static final Item TOMATO_JUICE;
    public static final Item TOMATO_PUREE;
    public static final Item TOMATO_SACK;
    public static final Item TOMATO_SEEDS;
    public static final Item TOMATO_SEED_SACK;
    public static final Item TORTILLA;
    public static final Item TORTILLA_CHIPS;
    public static final Item TORTILLA_WITH_CHEESE;
    public static final Item TORTILLA_WITH_JALAPENO_CHEESE;
    public static final Item TRAIL_MIX;
    public static final Item TROPICAL_PUNCH_BEVERAGE;
    public static final Item TROPICAL_PUNCH_BEVERAGE_POWDER;
    public static final Item TUMBLER;
    public static final Item TUNA_SANDWICH;
    public static final Item TURKISH_DELIGHT;
    public static final Item VANILLA_EXTRACT;
    public static final Item VANILLA_ICE_CREAM;
    public static final Item VANILLA_LATTE;
    public static final Item VANILLA_POD;
    public static final Item VANILLA_POD_SACK;
    public static final Item VANILLA_PUDDING;
    public static final Item VANILLA_SEEDS;
    public static final Item VANILLA_SEED_SACK;
    public static final Item VEGANBURGER;
    public static final Item VEGANBURGER_PATTY;
    public static final Item WAFFLE;
    public static final Item WARPED_BERRIES;
    public static final Item WART_PIE;
    public static final Item WATERMINT;
    public static final Item WEDGES;
    public static final Item WEDGES_POT;
    public static final Item WHITE_CANDY;
    public static final Item WHITE_CHOCOLATE;
    public static final Item WHITE_CHOCOLATE_COVERED_APPLE;
    public static final Item WHITE_WINE;
    public static final Item WINE_GLASS;
    public static final Item WOODEN_KNIFE;
    public static final Item WOODEN_SPOON;
    public static final Item WOODEN_TREE_TAP;
    public static final Item YEAST;
    public static final Item YEAST_SACK;
    public static final Item YELLOW_CANDY;

    private static Item registerBlock(String name, Block block) {
        return Registry.register(BuiltInRegistries.ITEM, ResourceLocation.fromNamespaceAndPath(Constants.MOD_ID, name), new BlockItem(block, new Item.Properties()));
    }
    private static Item registerItem(String name, Item item) {
        return Registry.register(BuiltInRegistries.ITEM, ResourceLocation.fromNamespaceAndPath(Constants.MOD_ID, name), item);
    }

    public static void init() {}
    
    static {
        ALMONDS = registerItem("almonds", new Item(new Item.Properties().food(ModFoodProperties.ALMONDS)));
        ALMOND_SACK = registerBlock("almond_sack", ModBlocks.ALMOND_SACK);
        ALMOND_SAPLING = registerBlock("almond_sapling", ModBlocks.ALMOND_SAPLING);
        AMERICANO = registerItem("americano", new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        APPLESAUCE = registerItem("applesauce", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.APPLESAUCE).stacksTo(1)));
        APPLE_ICECRUSH = registerItem("apple_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        APPLE_JUICE = registerItem("apple_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        APPLE_PIE = registerItem("apple_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        APPLE_RASPBERRY_ICECRUSH = registerItem("apple_raspberry_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        APPLE_RASPBERRY_PIE = registerItem("apple_raspberry_pie",  new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        APPLE_SAPLING = registerBlock("apple_sapling", ModBlocks.APPLE_SAPLING);
        APPLE_SODA = registerItem("apple_soda", new ConvertableItem(ModItems.SODA_CAN, new Item.Properties().stacksTo(16).food(ModFoodProperties.SODA).craftRemainder(SODA_CAN)));
        AVOCADO = registerItem("avocado", new Item(new Item.Properties().food(ModFoodProperties.AVOCADO)));
        AVOCADO_SACK = registerBlock("avocado_sack", ModBlocks.AVOCADO_SACK);
        AVOCADO_SAPLING = registerBlock("avocado_sapling",  ModBlocks.AVOCADO_SAPLING);
        BACON = registerItem("bacon", new Item(new Item.Properties().food(ModFoodProperties.BACON)));
        BACON_EGG_MUFFIN = registerItem("bacon_egg_muffin", new Item(new Item.Properties().food(ModFoodProperties.BACON_EGG_MUFFIN)));
        BACON_EGG_SANDWICH = registerItem("bacon_egg_sandwich", new Item(new Item.Properties().food(ModFoodProperties.BACON_EGG_SANDWICH)));
        BAKED_SWEET_POTATO = registerItem("baked_sweet_potato", new Item(new Item.Properties().food(ModFoodProperties.BAKED_SWEET_POTATO)));
        BANANA = registerItem("banana", new Item(new Item.Properties().food(ModFoodProperties.BANANA)));
        BANANA_ICE_CREAM = registerItem("banana_ice_cream",  new Item(new Item.Properties().food(ModFoodProperties.ICE_CREAM )));
        BANANA_MILKSHAKE = registerItem("banana_milkshake", new ConvertableItem(ModItems.BEVERAGE_CUP,  new Item.Properties().stacksTo(16).food(ModFoodProperties.MILKSHAKE).craftRemainder(BEVERAGE_CUP)));
        BANANA_SACK = registerBlock("banana_sack", ModBlocks.BANANA_SACK);
        BANANA_SAPLING = registerBlock("banana_sapling", ModBlocks.BANANA_SAPLING);
        BANANA_SMOOTHIE = registerItem("banana_smoothie", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.SMOOTHIE).craftRemainder(TUMBLER)));
        BARLEY_SEEDS = registerBlock("barley_seeds", ModBlocks.BARLEY_CROP);
        BARLEY_SEED_SACK = registerBlock("barley_seed_sack", ModBlocks.BARLEY_SEED_SACK);
        BAT_MEAT = registerItem("bat_meat", new Item(new Item.Properties().food(ModFoodProperties.BAT_MEAT)));
        BEANS = registerItem("beans", new Item(new Item.Properties().food(ModFoodProperties.BEANS)));
        BEAN_SACK = registerBlock("bean_sack", ModBlocks.BEAN_SACK);
        BEAN_SEEDS = registerBlock("bean_seeds", ModBlocks.BEAN_BUSH);
        BEEF_GOULASH = registerItem("beef_goulash",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.BEEF_GOULASH).stacksTo(1)));
        BEEF_RAVIOLI = registerItem("beef_ravioli", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.BEEF_RAVIOLI).stacksTo(1)));
        BEEF_STEW = registerItem("beef_stew", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.BEEF_STEW).stacksTo(1)));
        BEEF_SUB = registerItem("beef_sub", new Item(new Item.Properties().food(ModFoodProperties.SUB)));
        BEER = registerItem("beer",  new ConvertableDrinkItem(ModItems.WINE_GLASS, new Item.Properties().stacksTo(16).food(ModFoodProperties.BEER).craftRemainder(BEER_GLASS)));
        BEER_GLASS = registerItem("beer_glass", new Item(new Item.Properties()));
        BERRY_ICECRUSH = registerItem("berry_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        BERRY_JUICE = registerItem("berry_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        BERRY_PIE = registerItem("berry_pie",  new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        BERRY_SMOOTHIE = registerItem("berry_smoothie", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.SMOOTHIE).craftRemainder(TUMBLER)));
        BERRY_SODA = registerItem("berry_soda",  new ConvertableItem(ModItems.SODA_CAN, new Item.Properties().stacksTo(16).food(ModFoodProperties.SODA).craftRemainder(SODA_CAN)));
        BEVERAGE_CUP = registerItem("beverage_cup", new Item(new Item.Properties()));
        BLACK_CANDY = registerItem("black_candy",  new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        BLUEBERRIES = registerItem("blueberries", new Item(new Item.Properties().food(ModFoodProperties.BLUEBERRIES)));
        BLUEBERRY_SACK = registerBlock("blueberry_sack", ModBlocks.BLUEBERRY_SACK);
        BLUEBERRY_SEEDS = registerBlock("blueberry_seeds",  ModBlocks.BLUEBERRY_BUSH);
        BLUEBERRY_SEED_SACK = registerBlock("blueberry_seed_sack", ModBlocks.BLUEBERRY_SEED_SACK);
        BLUEBERRY_SYRUP = registerItem("blueberry_syrup",  new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.SYRUP).craftRemainder(Items.GLASS_BOTTLE)));
        BLUE_CANDY = registerItem("blue_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        BLUE_CUPCAKE = registerItem("blue_cupcake", new Item(new Item.Properties().food(ModFoodProperties.CUPCAKE)));
        BOTTLE = registerItem("bottle", new Item(new Item.Properties()));
        BOTTLED_BEER = registerItem("bottled_beer", new BottledItem(BEER_GLASS, BEER, new Item.Properties().stacksTo(1)));
        BOTTLED_CIDER = registerItem("bottled_cider", new BottledItem(TUMBLER, CIDER, new Item.Properties().stacksTo(1)));
        BOTTLED_RED_WINE = registerItem("bottled_red_wine", new BottledItem(WINE_GLASS, RED_WINE, new Item.Properties().stacksTo(1)));
        BOTTLED_WHITE_WINE = registerItem("bottled_white_wine", new BottledItem(WINE_GLASS, WHITE_WINE, new Item.Properties().stacksTo(1)));
        BREADSTICKS = registerItem("breadsticks", new Item(new Item.Properties().food(ModFoodProperties.BREADSTICKS)));
        BREADSTICKS_WITH_GLOWBERRY_JAM = registerItem("breadsticks_with_glowberry_jam", new Item(new Item.Properties().food(ModFoodProperties.BREADSTICKS)));
        BREADSTICKS_WITH_JAM = registerItem("breadsticks_with_jam", new Item(new Item.Properties().food(ModFoodProperties.BREADSTICKS)));
        BREADSTICKS_WITH_PEANUT_BUTTER = registerItem("breadsticks_with_peanut_butter", new Item(new Item.Properties().food(ModFoodProperties.BREADSTICKS)));
        BREAD_LOAF = registerItem("bread_loaf",  new Item(new Item.Properties().food(ModFoodProperties.BREAD_LOAF)));
        BREAKFAST_SUB = registerItem("breakfast_sub", new Item(new Item.Properties().food(ModFoodProperties.BREAKFAST_SUB)));
        BROWN_CANDY = registerItem("brown_candy",  new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        BUCKWHEAT = registerBlock("buckwheat", ModBlocks.BUCKWHEAT_CROP);
        BUCKWHEAT_SACK = registerBlock("buckwheat_sack", ModBlocks.BUCKWHEAT_SACK);
        BURGER_BUN = registerItem("burger_bun",  new Item(new Item.Properties().food(ModFoodProperties.BURGER_BUN)));
        BURNT_MARSHMALLOW_ON_A_STICK = registerItem("burnt_marshmallow_on_a_stick",  new ConvertableItem(Items.STICK, new Item.Properties().stacksTo(1).food(ModFoodProperties.MARSHMALLOW_ON_A_STICK).craftRemainder(Items.STICK)));
        BURRITO = registerItem("burrito", new Item(new Item.Properties().food(ModFoodProperties.BURRITO)));
        BUTTER = registerItem("butter",  new Item(new Item.Properties().food(ModFoodProperties.BUTTER)));
        CABBAGE = registerItem("cabbage", new Item(new Item.Properties().food(ModFoodProperties.CABBAGE)));
        CABBAGE_SACK = registerBlock("cabbage_sack", ModBlocks.CABBAGE_SACK);
        CABBAGE_SEEDS = registerBlock("cabbage_seeds",  ModBlocks.CABBAGE_CROP);
        CABBAGE_SEED_SACK = registerBlock("cabbage_seed_sack",  ModBlocks.CABBAGE_SEED_SACK);
        CAKE_WITH_CHERRIES= registerItem("cake_with_cherries", new BlockItem(ModBlocks.CAKE_WITH_CHERRIES, new Item.Properties().stacksTo(1)));
        CANDY_CORN = registerItem("candy_corn", new Item(new Item.Properties().food(ModFoodProperties.CANDY_CORN)));
        CANDY_CORN_BOWL = registerItem("candy_corn_bowl", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.CANDY_CORN_BOWL).craftRemainder(Items.BOWL)));
        CAPPUCCINO = registerItem("cappuccino",  new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        CAPPUCCINO_DRINK_MIX = registerItem("cappuccino_drink_mix", new Item(new Item.Properties()));
        CARTON = registerItem("carton", new Item(new Item.Properties()));
        CEREAL = registerItem("cereal",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.CEREAL).stacksTo(1)));
        CHEESE_BUCKET = registerItem("cheese_bucket",  new ConvertableDrinkItem(Items.BUCKET, new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET)));
        CHEESE_PIE = registerItem("cheese_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        CHEESE_SPREAD = registerItem("cheese_spread", new Item(new Item.Properties().craftRemainder(JAR)));
        CHEESE_TOASTIE = registerItem("cheese_toastie", new Item(new Item.Properties().food(ModFoodProperties.CHEESE_TOASTIE)));
        CHEESE_TORTELLINI = registerItem("cheese_tortellini", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.CHEESE_TORTELLINI).stacksTo(1)));
        CHEESE_WEDGE = registerItem("cheese_wedge", new Item(new Item.Properties().food(ModFoodProperties.CHEESE_WEDGE)));
        CHERRIES = registerItem("cherries",  new Item(new Item.Properties().food(ModFoodProperties.CHERRIES)));
        CHERRY_SACK = registerBlock("cherry_sack", ModBlocks.CHERRY_SACK);
        CHICKEN_FAJITA = registerItem("chicken_fajita", new Item(new Item.Properties().food(ModFoodProperties.CHICKEN_FAJITA)));
        CHICKEN_NUGGET = registerItem("chicken_nugget",  new Item(new Item.Properties().food(ModFoodProperties.CHICKEN_NUGGET)));
        CHICKEN_PIE = registerItem("chicken_pie",  new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        CHICKEN_SELECT = registerItem("chicken_select",  new ConvertableItem(ModItems.CHICKEN_SELECT_BOX, new Item.Properties().food(ModFoodProperties.CHICKEN_SELECT)));
        CHICKEN_SELECT_BOX = registerItem("chicken_select_box",  new Item(new Item.Properties()));
        CHICKEN_SOUP = registerItem("chicken_soup",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.CHICKEN_SOUP).stacksTo(1)));
        CHICKEN_SUB = registerItem("chicken_sub", new Item(new Item.Properties().food(ModFoodProperties.SUB)));
        CHILI = registerItem("chili", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.CHILI).stacksTo(1)));
        CHOCOLATE_BANANA_MUFFIN = registerItem("chocolate_banana_muffin", new Item(new Item.Properties().food(ModFoodProperties.CHOCOLATE_BANANA_MUFFIN)));
        CHOCOLATE_CAKE = registerItem("chocolate_cake", new BlockItem(ModBlocks.CHOCOLATE_CAKE, new Item.Properties().stacksTo(1)));
        CHOCOLATE_CHUNK_OATMEAL_COOKIE = registerItem("chocolate_chunk_oatmeal_cookie", new Item(new Item.Properties().food(ModFoodProperties.CHOCOLATE_CHUNK_OATMEAL_COOKIE)));
        CHOCOLATE_CHUNK_OATMEAL_COOKIE_SACK = registerBlock("chocolate_chunk_oatmeal_cookie_sack", ModBlocks.CHOCOLATE_CHUNK_OATMEAL_COOKIE_SACK);
        CHOCOLATE_DONUT = registerItem("chocolate_donut", new Item(new Item.Properties().food(ModFoodProperties.DONUT)));
        CHOCOLATE_ICE_CREAM = registerItem("chocolate_ice_cream",  new Item(new Item.Properties().food(ModFoodProperties.ICE_CREAM )));
        CHOCOLATE_MILKSHAKE = registerItem("chocolate_milkshake", new ConvertableItem(ModItems.BEVERAGE_CUP,  new Item.Properties().stacksTo(16).food(ModFoodProperties.MILKSHAKE).craftRemainder(BEVERAGE_CUP)));
        CHOCOLATE_PEANUT_BUTTER = registerItem("chocolate_peanut_butter",  new Item(new Item.Properties().craftRemainder(JAR)));
        CHOCOLATE_PIE = registerItem("chocolate_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        CHOCOLATE_PROTEIN_DRINK = registerItem("chocolate_protein_drink", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.BEVERAGE).craftRemainder(Items.GLASS_BOTTLE)));
        CHOCOLATE_PROTEIN_DRINK_MIX = registerItem("chocolate_protein_drink_mix", new Item(new Item.Properties()));
        CHOCOLATE_PUDDING = registerItem("chocolate_pudding",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.PUDDING).stacksTo(1)));
        CIDER = registerItem("cider", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.CIDER).craftRemainder(TUMBLER)));
        COCOA_BEVERAGE = registerItem("cocoa_beverage", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.BEVERAGE).craftRemainder(Items.GLASS_BOTTLE)));
        COCOA_BEVERAGE_POWDER = registerItem("cocoa_beverage_powder",  new Item(new Item.Properties()));
        COCONUT = registerItem("coconut",  new Item(new Item.Properties()));
        COCONUT_MEAT = registerItem("coconut_meat",  new Item(new Item.Properties().food(ModFoodProperties.COCONUT_MEAT)));
        COCONUT_MILK = registerItem("coconut_milk", new ConvertableItem(ModItems.BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.COCONUT_MILK).craftRemainder(BOTTLE)));
        COCONUT_SACK = registerBlock("coconut_sack", ModBlocks.COCONUT_SACK);
        COFFEE_BEANS = registerBlock("coffee_seeds",  ModBlocks.COFFEE_BUSH);
        COFFEE_BEAN_SACK = registerBlock("coffee_bean_sack",  ModBlocks.COFFEE_BEAN_SACK);
        COFFEE_DONUT = registerItem("coffee_donut", new Item(new Item.Properties().food(ModFoodProperties.DONUT)));
        COOKED_BACON = registerItem("cooked_bacon", new Item(new Item.Properties().food(ModFoodProperties.COOKED_BACON)));
        COOKED_BAT_MEAT = registerItem("cooked_bat_meat", new Item(new Item.Properties().food(ModFoodProperties.COOKED_BAT_MEAT)));
        COOKED_CHICKEN_NUGGET = registerItem("cooked_chicken_nugget",  new Item(new Item.Properties().food(ModFoodProperties.COOKED_CHICKEN_NUGGET)));
        COOKED_CHICKEN_PIECE = registerItem("cooked_chicken_piece", new Item(new Item.Properties().food(ModFoodProperties.COOKED_CHICKEN_PIECE)));
        COOKED_HAMBURGER_PATTY = registerItem("cooked_hamburger_patty",  new Item(new Item.Properties().food(ModFoodProperties.COOKED_HAMBURGER_PATTY)));
        COOKED_HOGLIN_MEAT = registerItem("cooked_hoglin_meat",  new Item(new Item.Properties().food(ModFoodProperties.COOKED_HOGLIN_MEAT)));
        COOKED_HOT_DOG_SAUSAGE = registerItem("cooked_hot_dog_sausage", new Item(new Item.Properties().food(ModFoodProperties.COOKED_HOT_DOG_SAUSAGE)));
        COOKED_MARSHMALLOW_ON_A_STICK = registerItem("cooked_marshmallow_on_a_stick", new ConvertableItem(Items.STICK, new Item.Properties().stacksTo(1).food(ModFoodProperties.MARSHMALLOW_ON_A_STICK).craftRemainder(Items.STICK)));
        COOKED_PUMPKIN_SEEDS = registerItem("cooked_pumpkin_seeds", new Item(new Item.Properties().food(ModFoodProperties.COOKED_PUMPKIN_SEEDS)));
        COOKED_SALTED_PUMPKIN_SEEDS = registerItem("cooked_salted_pumpkin_seeds",  new Item(new Item.Properties().food(ModFoodProperties.COOKED_PUMPKIN_SEEDS)));
        COOKED_SAUSAGE = registerItem("cooked_sausage",  new Item(new Item.Properties().food(ModFoodProperties.COOKED_SAUSAGE)));
        COOKED_VEGANBURGER_PATTY = registerItem("cooked_veganburger_patty",  new Item(new Item.Properties().food(ModFoodProperties.COOKED_VEGANBURGER_PATTY)));
        COOKED_WEDGES = registerItem("cooked_wedges",  new Item(new Item.Properties().food(ModFoodProperties.COOKED_WEDGES)));
        COPPER_KNIFE = registerItem("copper_knife", new Item(new Item.Properties()));
        CORN = registerBlock("corn", ModBlocks.CORN_CROP);
        CORNBREAD = registerItem("cornbread", new Item(new Item.Properties().food(ModFoodProperties.CORNBREAD)));
        CORN_COB = registerItem("corn_cob", new Item(new Item.Properties().food(ModFoodProperties.CORN_COB)));
        CORN_COB_SACK = registerBlock("corn_cob_sack",  ModBlocks.CORN_COB_SACK);
        CORN_FLOUR = registerItem("corn_flour", new Item(new Item.Properties()));
        CORN_FLOUR_SACK = registerBlock("corn_flour_sack",  ModBlocks.CORN_FLOUR_SACK);
        CORN_SACK = registerBlock("corn_sack_sack", ModBlocks.CORN_SACK);
        CRACKERS = registerItem("crackers", new Item(new Item.Properties().food(ModFoodProperties.CRACKERS)));
        CRACKERS_WITH_CHEESE = registerItem("crackers_with_cheese", new Item(new Item.Properties().food(ModFoodProperties.CRACKERS)));
        CRACKERS_WITH_CHOCOLATE_PEANUT_BUTTER = registerItem("crackers_with_chocolate_peanut_butter", new Item(new Item.Properties().food(ModFoodProperties.CRACKERS)));
        CRACKERS_WITH_GLOWBERRY_JAM = registerItem("crackers_with_glowberry_jam", new Item(new Item.Properties().food(ModFoodProperties.CRACKERS)));
        CRACKERS_WITH_JALAPENO_CHEESE = registerItem("crackers_with_jalapeno_cheese", new Item(new Item.Properties().food(ModFoodProperties.CRACKERS)));
        CRACKERS_WITH_JAM = registerItem("crackers_with_jam", new Item(new Item.Properties().food(ModFoodProperties.CRACKERS)));
        CRACKERS_WITH_PEANUT_BUTTER = registerItem("crackers_with_peanut_butter", new Item(new Item.Properties().food(ModFoodProperties.CRACKERS)));
        CRANBERRIES = registerItem("cranberries", new Item(new Item.Properties().food(ModFoodProperties.CRANBERRIES)));
        CRANBERRY_SACK = registerBlock("cranberry_sack",  ModBlocks.CRANBERRY_SACK);
        CRANBERRY_SEEDS = registerBlock("cranberry_seeds", ModBlocks.CRANBERRY_BUSH);
        CREAM_CARTON = registerItem("cream_carton",  new ConvertableDrinkItem(ModItems.CARTON, new Item.Properties().stacksTo(16).food(ModFoodProperties.CREAM_CARTON).craftRemainder(CARTON)));
        CREATIVE_HUNGER = registerItem("creative_hunger", new CreativeHungerItem(new Item.Properties().food(ModFoodProperties.CREATIVE_HUNGER)));
        CUSTARD = registerItem("custard",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.CUSTARD).stacksTo(1)));
        CUT_BREAD = registerItem("cut_bread",  new Item(new Item.Properties().food(ModFoodProperties.CUT_BREAD)));
        CUT_BREAD_WITH_CHEESE = registerItem("cut_bread_with_cheese", new Item(new Item.Properties().food(ModFoodProperties.CUT_BREAD)));
        CUT_BREAD_WITH_CHOCOLATE_PEANUT_BUTTER = registerItem("cut_bread_with_chocolate_peanut_butter",  new Item(new Item.Properties().food(ModFoodProperties.CUT_BREAD)));
        CUT_BREAD_WITH_GLOWBERRY_JAM = registerItem("cut_bread_with_glowberry_jam",  new Item(new Item.Properties().food(ModFoodProperties.CUT_BREAD)));
        CUT_BREAD_WITH_JALAPENO_CHEESE = registerItem("cut_bread_with_jalapeno_cheese", new Item(new Item.Properties().food(ModFoodProperties.CUT_BREAD)));
        CUT_BREAD_WITH_JAM = registerItem("cut_bread_with_jam", new Item(new Item.Properties().food(ModFoodProperties.CUT_BREAD)));
        CUT_BREAD_WITH_PEANUT_BUTTER = registerItem("cut_bread_with_peanut_butter", new Item(new Item.Properties().food(ModFoodProperties.CUT_BREAD)));
        CUT_FRIES = registerItem("cut_fries", new Item(new Item.Properties().food(ModFoodProperties.CUT_FRIES)));
        CUT_SWEET_POTATO = registerItem("cut_sweet_potato", new Item(new Item.Properties().food(ModFoodProperties.CUT_SWEET_POTATO)));
        CYAN_CANDY = registerItem("cyan_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        DARK_CHOCOLATE = registerItem("dark_chocolate", new Item(new Item.Properties().food(ModFoodProperties.CHOCOLATE_BAR)));
        DARK_CHOCOLATE_COVERED_APPLE = registerItem("dark_chocolate_covered_apple", new Item(new Item.Properties().food(ModFoodProperties.CHOCOLATE_COVERED)));
        DIAMOND_KNIFE = registerItem("diamond_knife", new Item(new Item.Properties()));
        DOUGH = registerItem("dough", new Item(new Item.Properties().food(ModFoodProperties.DOUGH)));
        DRIED_CRANBERRIES = registerItem("dried_cranberries",  new Item(new Item.Properties().food(ModFoodProperties.DRIED_CRANBERRIES)));
        DRIED_RAISENS = registerItem("dried_raisens",  new Item(new Item.Properties().food(ModFoodProperties.DRIED_RAISENS)));
        EGGPLANT = registerItem("eggplant",  new Item(new Item.Properties().food(ModFoodProperties.EGGPLANT)));
        EGGPLANT_SACK = registerBlock("eggplant_sack",  ModBlocks.EGGPLANT_SACK);
        EGGPLANT_SEEDS = registerBlock("eggplant_seeds", ModBlocks.EGGPLANT_BUSH);
        EGGPLANT_SEED_SACK = registerBlock("eggplant_seed_sack", ModBlocks.EGGPLANT_SEED_SACK);
        FLOUR = registerItem("flour", new Item(new Item.Properties()));
        FLOUR_SACK = registerBlock("flour_sack",  ModBlocks.FLOUR_SACK);
        FRIED_EGG = registerItem("fried_egg",  new Item(new Item.Properties().food(ModFoodProperties.FRIED_EGG)));
        FRIED_SQUID = registerItem("fried_squid",  new Item(new Item.Properties().food(ModFoodProperties.FRIED_SQUID)));
        FRIES = registerItem("fries", new ConvertableItem(ModItems.FRY_WRAPPER, new Item.Properties().food(ModFoodProperties.FRIES)));
        FRY_WRAPPER = registerItem("fry_wrapper", new Item(new Item.Properties()));
        FUNGUS_STEW = registerItem("fungus_stew", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.FUNGUS_STEW).stacksTo(1)));
        GARLIC = registerItem("garlic",  new Item(new Item.Properties().food(ModFoodProperties.GARLIC)));
        GARLIC_BULB = registerBlock("garlic_bulb", ModBlocks.GARLIC_CROP);
        GARLIC_MASHED_POTATOES = registerItem("garlic_mashed_potatoes", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.GARLIC_MASHED_POTATOES).stacksTo(1)));
        GARLIC_SACK = registerBlock("garlic_sack",  ModBlocks.GARLIC_SACK);
        GELATIN = registerItem("gelatin", new Item(new Item.Properties()));
        GHAST_COOKIE = registerItem("ghast_cookie", new Item(new Item.Properties().food(ModFoodProperties.GHAST_COOKIE)));
        GHERKIN = registerItem("gherkin", new Item(new Item.Properties().food(ModFoodProperties.GHERKIN)));
        GHERKIN_SACK = registerBlock("gherkin_sack", ModBlocks.GHERKIN_SACK);
        GHERKIN_SEEDS = registerBlock("gherkin_seeds", ModBlocks.GHERKIN_BUSH);
        GHERKIN_SEED_SACK = registerBlock("gherkin_seed_sack",  ModBlocks.GHERKIN_SEED_SACK);
        GLASS_SHARD = registerItem("glass_shard",  new Item(new Item.Properties()));
        GLOWBERRY_ICECRUSH = registerItem("glowberry_icecrush", new Item(new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        GLOWBERRY_JAM = registerItem("glowberry_jam", new Item(new Item.Properties().craftRemainder(JAR)));
        GLOWBERRY_JELLY_SANDWICH = registerItem("glowberry_jelly_sandwich", new Item(new Item.Properties().food(ModFoodProperties.GLOWBERRY_JELLY_SANDWICH)));
        GLOWBERRY_JUICE = registerItem("glowberry_juice", new Item(new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        GLOWBERRY_PIE = registerItem("glowberry_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        GLOWBERRY_SMOOTHIE = registerItem("glowberry_smoothie", new Item(new Item.Properties().stacksTo(16).food(ModFoodProperties.SMOOTHIE).craftRemainder(TUMBLER)));
        GLOWBERRY_SODA = registerItem("glowberry_soda", new Item(new Item.Properties().stacksTo(16).food(ModFoodProperties.SODA).craftRemainder(SODA_CAN)));
        GOLDEN_KNIFE = registerItem("golden_knife", new Item(new Item.Properties()));
        GRAPE = registerItem("grape", new Item(new Item.Properties().food(ModFoodProperties.GRAPE)));
        GRAPE_BEVERAGE = registerItem("grape_beverage", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.BEVERAGE).craftRemainder(Items.GLASS_BOTTLE)));
        GRAPE_BEVERAGE_POWDER = registerItem("grape_beverage_powder", new Item(new Item.Properties()));
        GRAPE_ICECRUSH = registerItem("grape_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        GRAPE_JUICE = registerItem("grape_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        GRAPE_SACK = registerBlock("grape_sack",  ModBlocks.GRAPE_SACK);
        GRAPE_SEEDS = registerBlock("grape_seeds", ModBlocks.GRAPE_BUSH);
        GRAPE_SEED_SACK = registerBlock("grape_seed_sack",  ModBlocks.GRAPE_SEED_SACK);
        GRAPE_SMOOTHIE = registerItem("grape_smoothie", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.SMOOTHIE).craftRemainder(TUMBLER)));
        GRAPE_SODA = registerItem("grape_soda", new ConvertableItem(ModItems.SODA_CAN, new Item.Properties().stacksTo(16).food(ModFoodProperties.SODA).craftRemainder(SODA_CAN)));
        GRAY_CANDY = registerItem("gray_candy",  new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        GREEN_CANDY = registerItem("green_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        GUACAMOLE = registerItem("guacamole", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.GUACAMOLE).stacksTo(1)));
        HAMBURGER = registerItem("hamburger", new Item(new Item.Properties().food(ModFoodProperties.HAMBURGER)));
        HAMBURGER_PATTY = registerItem("hamburger_patty", new Item(new Item.Properties().food(ModFoodProperties.HAMBURGER_PATTY)));
        HASH_BROWNS = registerItem("hash_browns", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.HASH_BROWNS).stacksTo(1)));
        HOGLIN_MEAT = registerItem("hoglin_meat",  new Item(new Item.Properties().food(ModFoodProperties.HOGLIN_MEAT)));
        HOPS = registerItem("hops", new Item(new Item.Properties().food(ModFoodProperties.HOPS)));
        HOPS_SACK = registerBlock("hops_sack",  ModBlocks.HOPS_SACK);
        HOPS_SEEDS = registerBlock("hops_seeds",  ModBlocks.HOPS_CROP);
        HOPS_SEED_SACK = registerBlock("hops_seed_sack",  ModBlocks.HOPS_SEED_SACK);
        HOT_BEVERAGE_CUP = registerItem("hot_beverage_cup", new Item(new Item.Properties()));
        HOT_COCOA = registerItem("hot_cocoa", new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        HOT_COFFEE = registerItem("hot_coffee", new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        HOT_DOG = registerItem("hot_dog",  new Item(new Item.Properties().food(ModFoodProperties.HOT_DOG)));
        HOT_DOG_BUN = registerItem("hot_dog_bun", new Item(new Item.Properties().food(ModFoodProperties.HOT_DOG_BUN)));
        HOT_DOG_SAUSAGE = registerItem("hot_dog_sausage", new Item(new Item.Properties().food(ModFoodProperties.HOT_DOG_SAUSAGE)));
        HOT_TEA = registerItem("hot_tea", new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        ICECRUSH_GLASS = registerItem("icecrush_glass", new Item(new Item.Properties()));
        ICED_DONUT = registerItem("iced_donut", new Item(new Item.Properties().food(ModFoodProperties.DONUT)));
        ICE_CREAM_BOWL = registerItem("ice_cream_bowl", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.ICE_CREAM_BOWL).stacksTo(1)));
        ICE_CREAM_CONE = registerItem("ice_cream_cone", new Item(new Item.Properties().food(ModFoodProperties.ICE_CREAM_CONE)));
        ICING = registerItem("icing", new Item(new Item.Properties()));
        IRON_KNIFE = registerItem("iron_knife", new Item(new Item.Properties()));
        JALAPENO_CHEESE_BUCKET = registerItem("jalapeno_cheese_bucket", new ConvertableDrinkItem(Items.BUCKET, new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET)));
        JALAPENO_CHEESE_PIE = registerItem("jalapeno_cheese_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        JALAPENO_CHEESE_SPREAD = registerItem("jalapeno_cheese_spread",  new Item(new Item.Properties().craftRemainder(JAR)));
        JALAPENO_CHEESE_TOASTIE = registerItem("jalapeno_cheese_toastie",  new Item(new Item.Properties().food(ModFoodProperties.CHEESE_TOASTIE)));
        JALAPENO_CHEESE_WEDGE = registerItem("jalapeno_cheese_wedge", new Item(new Item.Properties().food(ModFoodProperties.CHEESE_WEDGE)));
        JALAPENO_ROUND_CHEESE = registerItem("jalapeno_round_cheese", new Item(new Item.Properties().food(ModFoodProperties.ROUND_CHEESE)));
        JAM = registerItem("jam", new Item(new Item.Properties().craftRemainder(JAR)));
        JAR = registerItem("jar", new Item(new Item.Properties()));
        JELLY_SANDWICH = registerItem("jelly_sandwich", new Item(new Item.Properties().food(ModFoodProperties.JELLY_SANDWICH)));
        KEBAB = registerItem("kebab", new Item(new Item.Properties().food(ModFoodProperties.KEBAB)));
        KETCHUP = registerItem("ketchup",  new ConvertableItem(ModItems.BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.KETCHUP).craftRemainder(BOTTLE)));
        LARGE_BOWL = registerItem("large_bowl", new Item(new Item.Properties()));
        LARGE_PUMPKIN_PALE = registerItem("large_pumpkin_pale", new BlockItem(ModBlocks.LARGE_PUMPKIN_PALE, new Item.Properties().stacksTo(1)));
        LEMON = registerItem("lemon", new Item(new Item.Properties().food(ModFoodProperties.LEMON)));
        LEMON_ICECRUSH = registerItem("lemon_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        LEMON_JUICE = registerItem("lemon_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        LEMON_LIME_BEVERAGE = registerItem("lemon_lime_beverage", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.BEVERAGE).craftRemainder(Items.GLASS_BOTTLE)));
        LEMON_LIME_BEVERAGE_POWDER = registerItem("lemon_lime_beverage_powder",  new Item(new Item.Properties()));
        LEMON_PIE = registerItem("lemon_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        LEMON_SACK = registerBlock("lemon_sack",  ModBlocks.LEMON_SACK);
        LEMON_SAPLING = registerBlock("lemon_sapling", ModBlocks.LEMON_SAPLING);
        LEMON_SODA = registerItem("lemon_soda", new ConvertableItem(ModItems.SODA_CAN, new Item.Properties().stacksTo(16).food(ModFoodProperties.SODA).craftRemainder(SODA_CAN)));
        LETTUCE = registerItem("lettuce",  new Item(new Item.Properties().food(ModFoodProperties.LETTUCE)));
        LETTUCE_SACK = registerBlock("lettuce_sack",  ModBlocks.LETTUCE_SACK);
        LETTUCE_SEEDS = registerBlock("lettuce_seeds", ModBlocks.LETTUCE_CROP);
        LETTUCE_SEED_SACK = registerBlock("lettuce_seed_sack",  ModBlocks.LETTUCE_SEED_SACK);
        LIGHT_BLUE_CANDY = registerItem("light_blue_candy",  new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        LIGHT_GRAY_CANDY = registerItem("light_gray_candy",  new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        LIME_CANDY = registerItem("lime_candy",  new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        MACCHIATO = registerItem("macchiato", new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        MAGENTA_CANDY = registerItem("magenta_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        MAPLE_MUFFIN = registerItem("maple_muffin", new Item(new Item.Properties().food(ModFoodProperties.MAPLE_MUFFIN)));
        MAPLE_SAP_BUCKET = registerItem("maple_sap_bucket",  new ConvertableDrinkItem(Items.BUCKET, new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET)));
        MAPLE_SYRUP = registerItem("maple_syrup", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.SYRUP).craftRemainder(Items.GLASS_BOTTLE)));
        MAPLE_SYRUP_BUCKET = registerItem("maple_sap_bucket",  new ConvertableDrinkItem(Items.BUCKET, new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET)));
        MARSHMALLOW = registerItem("marshmallow", new Item(new Item.Properties().food(ModFoodProperties.MARSHMALLOW)));
        MARSHMALLOW_ON_A_STICK = registerItem("marshmallow_on_a_stick", new ConvertableItem(Items.STICK, new Item.Properties().stacksTo(1).food(ModFoodProperties.MARSHMALLOW_ON_A_STICK).craftRemainder(Items.STICK)));
        MASHED_POTATOES = registerItem("mashed_potatoes", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.MASHED_POTATOES).stacksTo(1)));
        MEAL_READY_TO_EAT = registerItem("meal_ready_to_eat", new MealReadyToEatItem(new Item.Properties().stacksTo(1)));
        MELON_ICECRUSH = registerItem("melon_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        MELON_JUICE = registerItem("melon_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        MILK_CARTON = registerItem("milk_carton",  new ConvertableDrinkItem(ModItems.CARTON, new Item.Properties().stacksTo(16).food(ModFoodProperties.MILK_CARTON).craftRemainder(CARTON)));
        MILK_CHOCOLATE = registerItem("milk_chocolate", new Item(new Item.Properties().food(ModFoodProperties.CHOCOLATE_BAR)));
        MILK_CHOCOLATE_COVERED_APPLE = registerItem("milk_chocolate_covered_apple", new Item(new Item.Properties().food(ModFoodProperties.CHOCOLATE_COVERED)));
        MIXED_FRUIT_ICECRUSH = registerItem("mixed_fruit_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        MIXED_FRUIT_JUICE = registerItem("mixed_fruit_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        MIXED_FRUIT_SMOOTHIE = registerItem("mixed_fruit_smoothie", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.SMOOTHIE).craftRemainder(TUMBLER)));
        MOCHA = registerItem("mocha", new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        MUFFIN_BUN = registerItem("muffin_bun", new Item(new Item.Properties().food(ModFoodProperties.MUFFIN_BUN)));
        NETHERITE_APPLE = registerItem("netherite_apple", new Item(new Item.Properties().food(ModFoodProperties.NETHERITE_APPLE)));
        NETHERITE_KNIFE = registerItem("netherite_knife", new Item(new Item.Properties()));
        NETHERWART_CHICKEN_SOUP = registerItem("netherwart_chicken_soup", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.NETHERWART_CHICKEN_SOUP).stacksTo(1)));
        NETHERWART_MUSHROOM_SOUP = registerItem("netherwart_mushroom_soup",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.NETHERWART_MUSHROOM_SOUP).stacksTo(1)));
        NETHER_COOKIE = registerItem("nether_cookie", new Item(new Item.Properties().food(ModFoodProperties.NETHER_COOKIE)));
        NETHER_COOKIE_SACK = registerBlock("nether_cookie_sack",  ModBlocks.NETHER_COOKIE_SACK);
        NOODLES = registerItem("noodles", new Item(new Item.Properties()));
        OATMEAL = registerItem("oatmeal", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.OATMEAL).stacksTo(1)));
        OATMEAL_COOKIE = registerItem("oatmeal_cookie", new Item(new Item.Properties().food(ModFoodProperties.OATMEAL_COOKIE)));
        OATMEAL_COOKIE_SACK = registerBlock("oatmeal_cookie_sack",  ModBlocks.OATMEAL_COOKIE_SACK);
        OATS = registerItem("oats", new Item(new Item.Properties().food(ModFoodProperties.OATS)));
        OAT_SACK = registerBlock("oat_sack", ModBlocks.OAT_SACK);
        OAT_SEEDS = registerBlock("oat_seeds", ModBlocks.OAT_CROP);
        OAT_SEED_SACK = registerBlock("oat_seed_sack", ModBlocks.OAT_SEED_SACK);
        OIL = registerItem("oil",  new ConvertableItem(ModItems.BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.OIL).craftRemainder(BOTTLE)));
        OLIVES = registerItem("olives",  new Item(new Item.Properties().food(ModFoodProperties.OLIVES)));
        OLIVES_SACK = registerBlock("olives_sack", ModBlocks.OLIVES_SACK);
        OLIVE_SAPLING = registerBlock("olive_sapling", ModBlocks.OLIVE_SAPLING);
        ONIGIRI = registerItem("onigiri",  new Item(new Item.Properties().food(ModFoodProperties.ONIGIRI)));
        ONION = registerItem("onion",  new Item(new Item.Properties().food(ModFoodProperties.ONION)));
        ONION_RINGS = registerItem("onion_rings", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.ONION_RINGS).stacksTo(1)));
        ONION_SACK = registerBlock("onion_sack", ModBlocks.ONION_SACK);
        ONION_SEEDS = registerBlock("onion_seeds", ModBlocks.ONION_CROP);
        ONION_SEED_SACK = registerBlock("onion_seed_sack", ModBlocks.ONION_SEED_SACK);
        ORANGE = registerItem("orange", new Item(new Item.Properties().food(ModFoodProperties.ORANGE)));
        ORANGE_BEVERAGE = registerItem("orange_beverage", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.BEVERAGE).craftRemainder(Items.GLASS_BOTTLE)));
        ORANGE_BEVERAGE_POWDER = registerItem("orange_beverage_powder", new Item(new Item.Properties()));
        ORANGE_CANDY = registerItem("orange_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        ORANGE_ICECRUSH = registerItem("orange_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        ORANGE_JELLY = registerItem("orange_jelly", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.JELLY).stacksTo(1)));
        ORANGE_JUICE = registerItem("orange_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        ORANGE_SACK = registerBlock("orange_sack", ModBlocks.ORANGE_SACK);
        ORANGE_SAPLING = registerBlock("orange_sapling", ModBlocks.ORANGE_SAPLING);
        ORANGE_SODA = registerItem("orange_soda", new ConvertableItem(ModItems.SODA_CAN, new Item.Properties().stacksTo(16).food(ModFoodProperties.SODA).craftRemainder(SODA_CAN)));
        PALM_SAPLING = registerBlock("palm_sapling", ModBlocks.PALM_SAPLING);
        PANCAKES = registerItem("pancakes",  new Item(new Item.Properties().food(ModFoodProperties.PANCAKES)));
        PANCAKE_MIX = registerItem("pancake_mix", new Item(new Item.Properties()));
        PASTA = registerItem("pasta",  new Item(new Item.Properties()));
        PEANUT = registerItem("peanut", new Item(new Item.Properties().food(ModFoodProperties.PEANUT)));
        PEANUT_BUTTER = registerItem("peanut_butter",  new Item(new Item.Properties().craftRemainder(JAR)));
        PEANUT_BUTTER_JELLY_SANDWICH = registerItem("peanut_butter_jelly_sandwich", new Item(new Item.Properties().food(ModFoodProperties.PEANUT_BUTTER_JELLY_SANDWICH)));
        PEANUT_SACK = registerBlock("peanut_sack", ModBlocks.PEANUT_SACK);
        PEANUT_SEEDS = registerBlock("peanut_seeds", ModBlocks.PEANUT_CROP);
        PEANUT_SEED_SACK = registerBlock("peanut_seed_sack", ModBlocks.PEANUT_SEED_SACK);
        PEPPER = registerItem("pepper", new Item(new Item.Properties().food(ModFoodProperties.PEPPER)));
        PEPPERMINT = registerItem("peppermint",  new Item(new Item.Properties().food(ModFoodProperties.PEPPERMINT)));
        PEPPERMINT_EXTRACT = registerItem("peppermint_extract", new ConvertableItem(ModItems.BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.PEPPERMINT_EXTRACT).craftRemainder(BOTTLE)));
        PEPPERMINT_RING = registerItem("peppermint_ring", new Item(new Item.Properties().food(ModFoodProperties.PEPPERMINT_RING)));
        PEPPERMINT_SEEDS = registerBlock("peppermint_seeds",  ModBlocks.PEPPERMINT_BUSH);
        PEPPER_SACK = registerBlock("pepper_sack", ModBlocks.PEPPER_SACK);
        PEPPER_SEEDS = registerBlock("pepper_seeds", ModBlocks.PEPPER_BUSH);
        PEPPER_SEED_SACK = registerBlock("pepper_seed_sack", ModBlocks.PEPPER_SEED_SACK);
        PICKLES = registerItem("pickles", new Item(new Item.Properties().food(ModFoodProperties.PICKLES)));
        PIE_BASE = registerItem("pie_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        PINK_CANDY = registerItem("pink_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        PINK_CUPCAKE = registerItem("pink_cupcake",  new Item(new Item.Properties().food(ModFoodProperties.CUPCAKE)));
        PINK_ICE_DONUT = registerItem("pink_ice_donut", new Item(new Item.Properties().food(ModFoodProperties.DONUT)));
        PITTA_BREAD = registerItem("pitta_bread",  new Item(new Item.Properties().food(ModFoodProperties.PITTA_BREAD)));
        PIZZA = registerItem("pizza", new Item(new Item.Properties().food(ModFoodProperties.PIZZA)));
        PIZZA_BASE = registerItem("pizza_base", new Item(new Item.Properties().food(ModFoodProperties.PIZZA_BASE)));
        PIZZA_SLICE = registerItem("pizza_slice", new Item(new Item.Properties().food(ModFoodProperties.PIZZA_SLICE)));
        PLAIN_DONUT = registerItem("plain_donut",  new Item(new Item.Properties().food(ModFoodProperties.DONUT)));
        PLUM = registerItem("plum", new Item(new Item.Properties().food(ModFoodProperties.PLUM)));
        PLUM_PIE = registerItem("plum_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        PLUM_SACK = registerBlock("plum_sack", ModBlocks.PLUM_SACK);
        PLUM_SAPLING = registerBlock("plum_sapling", ModBlocks.PLUM_SAPLING);
        POISONOUS_SWEET_POTATO = registerItem("poisonous_sweet_potato", new Item(new Item.Properties().food(ModFoodProperties.POISONOUS_SWEET_POTATO)));
        POISONOUS_SWEET_POTATO_SACK = registerBlock("poisonous_sweet_potato_sack", ModBlocks.POISONOUS_SWEET_POTATO_SACK);
        POISON_BERRIES = registerItem("poison_berries",  new BlockItem(ModBlocks.POISON_BERRY_BUSH, new Item.Properties().food(ModFoodProperties.POISON_BERRIES)));
        POISON_BERRY_SACK = registerBlock("poison_berry_sack", ModBlocks.POISON_BERRY_SACK);
        POPCORN = registerItem("popcorn", new Item(new Item.Properties().food(ModFoodProperties.POPCORN)));
        POPCORN_BUCKET = registerItem("popcorn_bucket", new ConvertableDrinkItem(Items.BUCKET, new Item.Properties().food(ModFoodProperties.POPCORN_BUCKET).stacksTo(1).craftRemainder(Items.BUCKET)));
        PORK_PIE = registerItem("pork_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        PORK_SAUSAGE_BURGER = registerItem("pork_sausage_burger", new Item(new Item.Properties().food(ModFoodProperties.PORK_SAUSAGE_BURGER)));
        POUND_CAKE = registerItem("pound_cake",  new BlockItem(ModBlocks.POUND_CAKE, new Item.Properties().stacksTo(1)));
        PRETZEL = registerItem("pretzel", new Item(new Item.Properties().food(ModFoodProperties.PRETZEL)));
        PRETZEL_NUGGETS = registerItem("pretzel_nuggets", new Item(new Item.Properties().food(ModFoodProperties.PRETZEL_NUGGETS)));
        PRETZEL_STICKS = registerItem("pretzel_sticks",  new Item(new Item.Properties().food(ModFoodProperties.PRETZEL_STICKS)));
        PULLED_BEEF_BURGER = registerItem("pulled_beef_burger",  new Item(new Item.Properties().food(ModFoodProperties.PULLED_BEEF_BURGER)));
        PULP = registerItem("pulp", new Item(new Item.Properties()));
        PURPLE_CANDY = registerItem("purple_candy",  new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        RAINBOW_CAKE = registerItem("rainbow_cake", new BlockItem(ModBlocks.RAINBOW_CAKE, new Item.Properties().stacksTo(1)));
        RAMEN_NOODLES = registerItem("ramen_noodles", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.RAMEN_NOODLES).stacksTo(1)));
        RASPBERRY = registerItem("raspberry", new Item(new Item.Properties().food(ModFoodProperties.RASPBERRY)));
        RASPBERRY_SACK = registerBlock("raspberry_sack", ModBlocks.RASPBERRY_SACK);
        RASPBERRY_SEEDS = registerBlock("raspberry_seeds", ModBlocks.RASPBERRY_BUSH);
        RASPBERRY_SEED_SACK = registerBlock("raspberry_seed_sack",  ModBlocks.RASPBERRY_SEED_SACK);
        RASPBERRY_SMOOTHIE = registerItem("raspberry_smoothie", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.SMOOTHIE).craftRemainder(TUMBLER)));
        RASPBERRY_SYRUP = registerItem("raspberry_syrup", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.SYRUP).craftRemainder(Items.GLASS_BOTTLE)));
        REDWHITEBLUE_CAKE = registerItem("redwhiteblue_cake",  new BlockItem(ModBlocks.REDWHITEBLUE_CAKE, new Item.Properties().stacksTo(1)));
        RED_CANDY = registerItem("red_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        RED_WINE = registerItem("red_wine",  new ConvertableDrinkItem(ModItems.WINE_GLASS, new Item.Properties().stacksTo(16).food(ModFoodProperties.WINE).craftRemainder(WINE_GLASS)));
        RICE = registerItem("rice", new Item(new Item.Properties().food(ModFoodProperties.RICE)));
        RICE_PUDDING = registerItem("rice_pudding", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.PUDDING).stacksTo(1)));
        RICE_SACK = registerBlock("rice_sack", ModBlocks.RICE_SACK);
        RICE_SEEDS = registerBlock("rice_seeds", ModBlocks.RICE_CROP);
        RICE_SEED_SACK = registerBlock("rice_seed_sack", ModBlocks.RICE_SEED_SACK);
        ROASTED_PEANUT = registerItem("roasted_peanut",  new Item(new Item.Properties().food(ModFoodProperties.ROASTED_PEANUT)));
        ROASTED_SOYBEANS = registerItem("roasted_soybeans",  new Item(new Item.Properties().food(ModFoodProperties.ROASTED_SOYBEANS)));
        ROASTED_SUNFLOWER_SEEDS = registerItem("roasted_sunflower_seeds", new SunflowerSeedsItem(new Item.Properties().food(ModFoodProperties.ROASTED_SUNFLOWER_SEEDS)));
        ROTTEN_PORKCHOP = registerItem("rotten_porkchop",  new Item(new Item.Properties().food(ModFoodProperties.ROTTEN_PORKCHOP)));
        ROUND_CHEESE = registerItem("round_cheese", new Item(new Item.Properties().food(ModFoodProperties.ROUND_CHEESE)));
        SALT = registerItem("salt",  new Item(new Item.Properties()));
        SASHIMI = registerItem("sashimi", new Item(new Item.Properties().food(ModFoodProperties.SASHIMI)));
        SAUSAGE = registerItem("sausage", new Item(new Item.Properties().food(ModFoodProperties.SAUSAGE)));
        SAUSAGE_EGG_MUFFIN = registerItem("sausage_egg_muffin", new Item(new Item.Properties().food(ModFoodProperties.SAUSAGE_EGG_MUFFIN)));
        SAUSAGE_EGG_SANDWICH = registerItem("sausage_egg_sandwich",  new Item(new Item.Properties().food(ModFoodProperties.SAUSAGE_EGG_SANDWICH)));
        SHROOMLIGHT_SLICES = registerItem("shroomlight_slices",  new Item(new Item.Properties().food(ModFoodProperties.SHROOMLIGHT_SLICES)));
        SMALL_PUMPKIN_PALE = registerItem("small_pumpkin_pale", new BlockItem(ModBlocks.SMALL_PUMPKIN_PALE, new Item.Properties().stacksTo(1)));
        SMOKED_ALMONDS = registerItem("smoked_almonds", new Item(new Item.Properties().food(ModFoodProperties.SMOKED_ALMONDS)));
        SODA_CAN = registerItem("soda_can", new Item(new Item.Properties()));
        SOYBEANS = registerBlock("soybeans", ModBlocks.SOYBEAN_BUSH);
        SOYBEAN_SACK = registerBlock("soybean_sack",  ModBlocks.SOYBEAN_SACK);
        SPAGHETTI = registerItem("spaghetti",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.SPAGHETTI).stacksTo(1)));
        SPAGHETTI_WITH_MEATBALLS = registerItem("spaghetti_with_meatballs",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.SPAGHETTI_WITH_MEATBALLS).stacksTo(1)));
        SPARKLING_WATER_BOTTLE = registerItem("sparkling_water_bottle",  new ConvertableItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.SPARKLING_WATER_BOTTLE).craftRemainder(Items.GLASS_BOTTLE)));
        SPARKLING_WATER_BUCKET = registerItem("sparkling_water_bucket", new ConvertableDrinkItem(Items.BUCKET, new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET)));
        SPEARMINT = registerBlock("spearmint", ModBlocks.SPEARMINT);
        SPINACH = registerItem("spinach", new Item(new Item.Properties().food(ModFoodProperties.SPINACH)));
        SPINACH_FETTUCCINE = registerItem("spinach_fettuccine",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.SPINACH_FETTUCCINE).stacksTo(1)));
        SPINACH_SACK = registerBlock("spinach_sack", ModBlocks.SPINACH_SACK);
        SPINACH_SEEDS = registerBlock("spinach_seeds", ModBlocks.SPINACH_CROP);
        SPINACH_SEED_SACK = registerBlock("spinach_seed_sack",  ModBlocks.SPINACH_SEED_SACK);
        SQUID = registerItem("squid", new Item(new Item.Properties().food(ModFoodProperties.SQUID)));
        STARCH = registerItem("starch", new Item(new Item.Properties()));
        STEAK_PIE = registerItem("steak_pie",  new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        STONE_KNIFE = registerItem("stone_knife", new Item(new Item.Properties()));
        STRAWBERRY = registerItem("strawberry",  new Item(new Item.Properties().food(ModFoodProperties.STRAWBERRY)));
        STRAWBERRY_DONUT = registerItem("strawberry_donut", new Item(new Item.Properties().food(ModFoodProperties.DONUT)));
        STRAWBERRY_ICECRUSH = registerItem("strawberry_icecrush", new ConvertableItem(ModItems.ICECRUSH_GLASS,  new Item.Properties().stacksTo(16).food(ModFoodProperties.ICECRUSH).craftRemainder(ICECRUSH_GLASS)));
        STRAWBERRY_ICE_CREAM = registerItem("strawberry_ice_cream", new Item(new Item.Properties().food(ModFoodProperties.ICE_CREAM )));
        STRAWBERRY_JELLY = registerItem("strawberry_jelly", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.JELLY).stacksTo(1)));
        STRAWBERRY_JUICE = registerItem("strawberry_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        STRAWBERRY_MILKSHAKE = registerItem("strawberry_milkshake", new ConvertableItem(ModItems.BEVERAGE_CUP,  new Item.Properties().stacksTo(16).food(ModFoodProperties.MILKSHAKE).craftRemainder(BEVERAGE_CUP)));
        STRAWBERRY_PIE = registerItem("strawberry_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        STRAWBERRY_SACK = registerBlock("strawberry_sack", ModBlocks.STRAWBERRY_SACK);
        STRAWBERRY_SEEDS = registerBlock("strawberry_seeds", ModBlocks.STRAWBERRY_BUSH);
        STRAWBERRY_SEED_SACK = registerBlock("strawberry_seed_sack",  ModBlocks.STRAWBERRY_SEED_SACK);
        STRAWBERRY_SMOOTHIE = registerItem("strawberry_smoothie", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.SMOOTHIE).craftRemainder(TUMBLER)));
        STRAWBERRY_SODA = registerItem("strawberry_soda", new ConvertableItem(ModItems.SODA_CAN, new Item.Properties().stacksTo(16).food(ModFoodProperties.SODA).craftRemainder(SODA_CAN)));
        STRAWBERRY_SYRUP = registerItem("strawberry_syrup", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.SYRUP).craftRemainder(Items.GLASS_BOTTLE)));
        SUB_BUN = registerItem("sub_bun", new Item(new Item.Properties().food(ModFoodProperties.SUB_BUN)));
        SUB_WRAPPER = registerItem("sub_wrapper", new Item(new Item.Properties()));
        SUGAR_COOKIE = registerItem("sugar_cookie",  new Item(new Item.Properties().food(ModFoodProperties.SUGAR_COOKIE)));
        SUGAR_COOKIE_SACK = registerBlock("sugar_cookie_sack", ModBlocks.SUGAR_COOKIE_SACK);
        SUSHI = registerItem("sushi", new Item(new Item.Properties().food(ModFoodProperties.SUSHI)));
        SWEET_MASHED_POTATOES = registerItem("sweet_mashed_potatoes", new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.SWEET_MASHED_POTATOES).stacksTo(1)));
        SWEET_POTATO = registerItem("sweet_potato", new Item(new Item.Properties().food(ModFoodProperties.SWEET_POTATO)));
        SWEET_POTATO_FRIES = registerItem("sweet_potato_fries",  new ConvertableItem(ModItems.FRY_WRAPPER, new Item.Properties().food(ModFoodProperties.FRIES)));
        SWEET_POTATO_SACK = registerBlock("sweet_potato_sack",  ModBlocks.SWEET_POTATO_SACK);
        TACO = registerItem("taco", new Item(new Item.Properties().food(ModFoodProperties.TACO)));
        TEA_LEAF_SACK = registerBlock("tea_leaf_sack",  ModBlocks.TEA_LEAF_SACK);
        TEA_LEAVES = registerItem("tea_leaves", new Item(new Item.Properties().food(ModFoodProperties.TEA_LEAVES)));
        TEA_SEEDS = registerBlock("tea_seeds", ModBlocks.TEA_BUSH);
        TEA_SEED_SACK = registerBlock("tea_seed_sack", ModBlocks.TEA_SEED_SACK);
        TOAST = registerItem("toast", new Item(new Item.Properties().food(ModFoodProperties.TOAST)));
        TOFFEE = registerItem("toffee", new Item(new Item.Properties().food(ModFoodProperties.TOFFEE)));
        TOFFEE_DONUT = registerItem("toffee_donut", new Item(new Item.Properties().food(ModFoodProperties.DONUT)));
        TOFFEE_ICE_CREAM = registerItem("toffee_ice_cream",  new Item(new Item.Properties().food(ModFoodProperties.ICE_CREAM )));
        TOFFEE_LATTE = registerItem("toffee_latte", new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        TOFFEE_PIE = registerItem("toffee_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        TOMATO = registerItem("tomato", new Item(new Item.Properties().food(ModFoodProperties.TOMATO)));
        TOMATO_JUICE = registerItem("tomato_juice", new ConvertableDrinkItem(ModItems.TUMBLER, new Item.Properties().stacksTo(16).food(ModFoodProperties.JUICE).craftRemainder(TUMBLER)));
        TOMATO_PUREE = registerItem("tomato_puree", new Item(new Item.Properties().food(ModFoodProperties.TOMATO_PUREE)));
        TOMATO_SACK = registerBlock("tomato_sack", ModBlocks.TOMATO_SACK);
        TOMATO_SEEDS = registerBlock("tomato_seeds", ModBlocks.TOMATO_BUSH);
        TOMATO_SEED_SACK = registerBlock("tomato_seed_sack", ModBlocks.TOMATO_SEED_SACK);
        TORTILLA = registerItem("tortilla", new Item(new Item.Properties().food(ModFoodProperties.TORTILLA)));
        TORTILLA_CHIPS = registerItem("tortilla_chips",  new Item(new Item.Properties().food(ModFoodProperties.TORTILLA_CHIPS)));
        TORTILLA_WITH_CHEESE = registerItem("tortilla_with_cheese", new Item(new Item.Properties().food(ModFoodProperties.TORTILLA)));
        TORTILLA_WITH_JALAPENO_CHEESE = registerItem("tortilla_with_jalapeno_cheese", new Item(new Item.Properties().food(ModFoodProperties.TORTILLA)));
        TRAIL_MIX = registerItem("trail_mix", new Item(new Item.Properties().food(ModFoodProperties.TRAIL_MIX)));
        TROPICAL_PUNCH_BEVERAGE = registerItem("tropical_punch_beverage", new ConvertableDrinkItem(Items.GLASS_BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.BEVERAGE).craftRemainder(Items.GLASS_BOTTLE)));
        TROPICAL_PUNCH_BEVERAGE_POWDER = registerItem("tropical_punch_beverage_powder",  new Item(new Item.Properties()));
        TUMBLER = registerItem("tumbler_glass", new Item(new Item.Properties()));
        TUNA_SANDWICH = registerItem("tuna_sandwich", new Item(new Item.Properties().food(ModFoodProperties.TUNA_SANDWICH)));
        TURKISH_DELIGHT = registerItem("turkish_delight",  new Item(new Item.Properties().food(ModFoodProperties.TURKISH_DELIGHT)));
        VANILLA_EXTRACT = registerItem("vanilla_extract",  new ConvertableItem(ModItems.BOTTLE,   new Item.Properties().stacksTo(16).food(ModFoodProperties.VANILLA_EXTRACT).craftRemainder(BOTTLE)));
        VANILLA_ICE_CREAM = registerItem("vanilla_ice_cream", new Item(new Item.Properties().food(ModFoodProperties.ICE_CREAM )));
        VANILLA_LATTE = registerItem("vanilla_latte", new ConvertableItem(ModItems.HOT_BEVERAGE_CUP, new Item.Properties().stacksTo(16).food(ModFoodProperties.HOT_BEVERAGE).craftRemainder(HOT_BEVERAGE_CUP)));
        VANILLA_POD = registerItem("vanilla_pod", new Item(new Item.Properties()));
        VANILLA_POD_SACK = registerBlock("vanilla_pod_sack", ModBlocks.VANILLA_POD_SACK);
        VANILLA_PUDDING = registerItem("vanilla_pudding",  new ConvertableItem(Items.BOWL, new Item.Properties().food(ModFoodProperties.PUDDING).stacksTo(1)));
        VANILLA_SEEDS = registerBlock("vanilla_seeds", ModBlocks.VANILLA_BUSH);
        VANILLA_SEED_SACK = registerBlock("vanilla_seed_sack", ModBlocks.VANILLA_SEED_SACK);
        VEGANBURGER = registerItem("veganburger", new Item(new Item.Properties().food(ModFoodProperties.VEGANBURGER)));
        VEGANBURGER_PATTY = registerItem("veganburger_patty", new Item(new Item.Properties().food(ModFoodProperties.VEGANBURGER_PATTY)));
        WAFFLE = registerItem("waffle", new Item(new Item.Properties().food(ModFoodProperties.WAFFLE)));
        WARPED_BERRIES = registerItem("warped_berries",  new Item(new Item.Properties().food(ModFoodProperties.WARPED_BERRIES)));
        WART_PIE = registerItem("wart_pie", new Item(new Item.Properties().food(ModFoodProperties.PIE)));
        WATERMINT = registerBlock("watermint", ModBlocks.WATERMINT);
        WEDGES = registerItem("wedges", new Item(new Item.Properties().food(ModFoodProperties.WEDGES)));
        WEDGES_POT = registerItem("wedges_pot",  new Item(new Item.Properties().food(ModFoodProperties.WEDGES_POT)));
        WHITE_CANDY = registerItem("white_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
        WHITE_CHOCOLATE = registerItem("white_chocolate", new Item(new Item.Properties().food(ModFoodProperties.CHOCOLATE_BAR)));
        WHITE_CHOCOLATE_COVERED_APPLE = registerItem("white_chocolate_covered_apple", new Item(new Item.Properties().food(ModFoodProperties.CHOCOLATE_COVERED)));
        WHITE_WINE = registerItem("white_wine",  new ConvertableDrinkItem(ModItems.WINE_GLASS, new Item.Properties().stacksTo(16).food(ModFoodProperties.WINE).craftRemainder(WINE_GLASS)));
        WINE_GLASS = registerItem("wine_glass",  new Item(new Item.Properties()));
        WOODEN_KNIFE = registerItem("wooden_knife", new Item(new Item.Properties()));
        WOODEN_SPOON = registerItem("wooden_spoon", new Item(new Item.Properties()));
        WOODEN_TREE_TAP = registerItem("wooden_tree_tap",  new BlockItem(ModBlocks.WOODEN_TREE_TAP, new Item.Properties()));
        YEAST = registerItem("yeast", new Item(new Item.Properties().food(ModFoodProperties.YEAST)));
        YEAST_SACK = registerBlock("yeast_sack", ModBlocks.YEAST_SACK);
        YELLOW_CANDY = registerItem("yellow_candy", new Item(new Item.Properties().food(ModFoodProperties.CANDY)));
    }
}
